title: PoppinL
email: poppinlp@gmail.com
description: "2B青年欢乐多"

source: ./
destination: ./_site
layouts: ./_layouts
encoding: "utf-8"
markdown_ext: "markdown,md"
markdown: kramdown
highlighter: pygments
sass:
    sass_dir: css
    style: compressed
